spring:
  profiles:
    active:
      - dev
---
server:
  port: 3355
spring:
  application:
    name: CH-MICRO-SERVER-DEV
  #开发环境
  profiles: dev
---
server:
  port: 3356
spring:
  application:
    name: CH-MICRO-SERVER-TEST
  #测试环境
  profiles: test

